<a href="https://colab.research.google.com/github/pankovakris/coursera/blob/main/Stepik_CV_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.zeros(2, 7)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [3]:
torch.ones(2, 2, 3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [4]:
x = torch.tensor([[1, 2, 3,], [4, 5, 6]])

In [5]:
x.shape

torch.Size([2, 3])

In [6]:
x[1]

tensor([4, 5, 6])

In [7]:
x[0, 0]

tensor(1)

In [8]:
x + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [9]:
x ** 2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [10]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [11]:
x > 3

tensor([[False, False, False],
        [ True,  True,  True]])

In [12]:
mask = x > 3

In [13]:
print(x[mask])
x[x > 1]
#остаются только элементы, подходящие под маску

tensor([4, 5, 6])


tensor([2, 3, 4, 5, 6])

In [14]:
y = x #создаст ссылку на x, не прикольно

In [15]:
y = x.clone() #создаст отдельный тензор, равный x

In [16]:
x.dtype

torch.int64

In [17]:
# если вдруг изначально тензор был в float32, то можно перевести в 64 с помощью 
# x.double()
# обратно в инт
# x.int()
# и во float соотв
# x.float()

In [18]:
torch.cuda.is_available()

True

In [19]:
torch.device('cuda:0') #переводим девайс etc

device(type='cuda', index=0)